// =============================================================================
// ELEMENTS.JS — Periodic Table Data (ES Module)
// Contains basic info for the periodic table elements (first 86).
// =============================================================================

export const elements = [
    { symbol: 'H', name: 'Hydrogen', group: 1, period: 1, type: 'nonmetal' },
    { symbol: 'He', name: 'Helium', group: 18, period: 1, type: 'noble-gas' },
    { symbol: 'Li', name: 'Lithium', group: 1, period: 2, type: 'alkali-metal' },
    { symbol: 'Be', name: 'Beryllium', group: 2, period: 2, type: 'alkaline-earth' },
    { symbol: 'B', name: 'Boron', group: 13, period: 2, type: 'metalloid' },
    { symbol: 'C', name: 'Carbon', group: 14, period: 2, type: 'nonmetal' },
    { symbol: 'N', name: 'Nitrogen', group: 15, period: 2, type: 'nonmetal' },
    { symbol: 'O', name: 'Oxygen', group: 16, period: 2, type: 'nonmetal' },
    { symbol: 'F', name: 'Fluorine', group: 17, period: 2, type: 'halogen' },
    { symbol: 'Ne', name: 'Neon', group: 18, period: 2, type: 'noble-gas' },
    { symbol: 'Na', name: 'Sodium', group: 1, period: 3, type: 'alkali-metal' },
    { symbol: 'Mg', name: 'Magnesium', group: 2, period: 3, type: 'alkaline-earth' },
    { symbol: 'Al', name: 'Aluminum', group: 13, period: 3, type: 'post-transition' },
    { symbol: 'Si', name: 'Silicon', group: 14, period: 3, type: 'metalloid' },
    { symbol: 'P', name: 'Phosphorus', group: 15, period: 3, type: 'nonmetal' },
    { symbol: 'S', name: 'Sulfur', group: 16, period: 3, type: 'nonmetal' },
    { symbol: 'Cl', name: 'Chlorine', group: 17, period: 3, type: 'halogen' },
    { symbol: 'Ar', name: 'Argon', group: 18, period: 3, type: 'noble-gas' },
    { symbol: 'K', name: 'Potassium', group: 1, period: 4, type: 'alkali-metal' },
    { symbol: 'Ca', name: 'Calcium', group: 2, period: 4, type: 'alkaline-earth' },
    { symbol: 'Sc', name: 'Scandium', group: 3, period: 4, type: 'transition-metal' },
    { symbol: 'Ti', name: 'Titanium', group: 4, period: 4, type: 'transition-metal' },
    { symbol: 'V', name: 'Vanadium', group: 5, period: 4, type: 'transition-metal' },
    { symbol: 'Cr', name: 'Chromium', group: 6, period: 4, type: 'transition-metal' },
    { symbol: 'Mn', name: 'Manganese', group: 7, period: 4, type: 'transition-metal' },
    { symbol: 'Fe', name: 'Iron', group: 8, period: 4, type: 'transition-metal' },
    { symbol: 'Co', name: 'Cobalt', group: 9, period: 4, type: 'transition-metal' },
    { symbol: 'Ni', name: 'Nickel', group: 10, period: 4, type: 'transition-metal' },
    { symbol: 'Cu', name: 'Copper', group: 11, period: 4, type: 'transition-metal' },
    { symbol: 'Zn', name: 'Zinc', group: 12, period: 4, type: 'transition-metal' },
    { symbol: 'Ga', name: 'Gallium', group: 13, period: 4, type: 'post-transition' },
    { symbol: 'Ge', name: 'Germanium', group: 14, period: 4, type: 'metalloid' },
    { symbol: 'As', name: 'Arsenic', group: 15, period: 4, type: 'metalloid' },
    { symbol: 'Se', name: 'Selenium', group: 16, period: 4, type: 'nonmetal' },
    { symbol: 'Br', name: 'Bromine', group: 17, period: 4, type: 'halogen' },
    { symbol: 'Kr', name: 'Krypton', group: 18, period: 4, type: 'noble-gas' },
    { symbol: 'Rb', name: 'Rubidium', group: 1, period: 5, type: 'alkali-metal' },
    { symbol: 'Sr', name: 'Strontium', group: 2, period: 5, type: 'alkaline-earth' },
    { symbol: 'Y', name: 'Yttrium', group: 3, period: 5, type: 'transition-metal' },
    { symbol: 'Zr', name: 'Zirconium', group: 4, period: 5, type: 'transition-metal' },
    { symbol: 'Nb', name: 'Niobium', group: 5, period: 5, type: 'transition-metal' },
    { symbol: 'Mo', name: 'Molybdenum', group: 6, period: 5, type: 'transition-metal' },
    { symbol: 'Tc', name: 'Technetium', group: 7, period: 5, type: 'transition-metal' },
    { symbol: 'Ru', name: 'Ruthenium', group: 8, period: 5, type: 'transition-metal' },
    { symbol: 'Rh', name: 'Rhodium', group: 9, period: 5, type: 'transition-metal' },
    { symbol: 'Pd', name: 'Palladium', group: 10, period: 5, type: 'transition-metal' },
    { symbol: 'Ag', name: 'Silver', group: 11, period: 5, type: 'transition-metal' },
    { symbol: 'Cd', name: 'Cadmium', group: 12, period: 5, type: 'transition-metal' },
    { symbol: 'In', name: 'Indium', group: 13, period: 5, type: 'post-transition' },
    { symbol: 'Sn', name: 'Tin', group: 14, period: 5, type: 'post-transition' },
    { symbol: 'Sb', name: 'Antimony', group: 15, period: 5, type: 'metalloid' },
    { symbol: 'Te', name: 'Tellurium', group: 16, period: 5, type: 'metalloid' },
    { symbol: 'I', name: 'Iodine', group: 17, period: 5, type: 'halogen' },
    { symbol: 'Xe', name: 'Xenon', group: 18, period: 5, type: 'noble-gas' },
    { symbol: 'Cs', name: 'Cesium', group: 1, period: 6, type: 'alkali-metal' },
    { symbol: 'Ba', name: 'Barium', group: 2, period: 6, type: 'alkaline-earth' },
    // Lanthanides ignored for simplicity, jumping to Hafnium
    { symbol: 'Hf', name: 'Hafnium', group: 4, period: 6, type: 'transition-metal' },
    { symbol: 'Ta', name: 'Tantalum', group: 5, period: 6, type: 'transition-metal' },
    { symbol: 'W', name: 'Tungsten', group: 6, period: 6, type: 'transition-metal' },
    { symbol: 'Re', name: 'Rhenium', group: 7, period: 6, type: 'transition-metal' },
    { symbol: 'Os', name: 'Osmium', group: 8, period: 6, type: 'transition-metal' },
    { symbol: 'Ir', name: 'Iridium', group: 9, period: 6, type: 'transition-metal' },
    { symbol: 'Pt', name: 'Platinum', group: 10, period: 6, type: 'transition-metal' },
    { symbol: 'Au', name: 'Gold', group: 11, period: 6, type: 'transition-metal' },
    { symbol: 'Hg', name: 'Mercury', group: 12, period: 6, type: 'transition-metal' },
    { symbol: 'Tl', name: 'Thallium', group: 13, period: 6, type: 'post-transition' },
    { symbol: 'Pb', name: 'Lead', group: 14, period: 6, type: 'post-transition' },
    { symbol: 'Bi', name: 'Bismuth', group: 15, period: 6, type: 'post-transition' },
    { symbol: 'Po', name: 'Polonium', group: 16, period: 6, type: 'metalloid' },
    { symbol: 'At', name: 'Astatine', group: 17, period: 6, type: 'halogen' },
    { symbol: 'Rn', name: 'Radon', group: 18, period: 6, type: 'noble-gas' }
];
